const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const playwright = require('playwright');
const { selectedBrowser, browserOptions, registerFixtureAccount, authenticatedRequest, setFixtureRoles } = require('./local-account.cjs');
const origin = process.env.RCC_WEB_URL;
const output = process.env.RCC_E2E_OUTPUT || '/tmp/rcc-approval-role-browser';
(async () => {
  fs.mkdirSync(output, { recursive: true });
  const browser = await selectedBrowser(playwright).launch(browserOptions());
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
  const checks=[], errors=[]; let page;
  const stableScreenshot=async(name)=>{
    await page.getByLabel('角色名称',{exact:true}).waitFor();
    await page.mouse.move(0,0);
    await page.waitForFunction(()=>document.querySelectorAll('[data-sonner-toast]').length===0,undefined,{timeout:7000});
    await page.evaluate(async()=>Promise.all(document.getAnimations().map(animation=>animation.finished.catch(()=>{}))));
    const geometry=await page.getByRole('dialog',{name:'编辑审批角色',exact:true}).boundingBox();
    assert.ok(geometry && geometry.x>=0 && geometry.x+geometry.width<=page.viewportSize().width+1,'drawer extends outside viewport');
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'page has horizontal overflow');
    await page.screenshot({path:path.join(output,name)});
  };
  try {
    const admin=await registerFixtureAccount(context, origin);
    const memberContext=await browser.newContext();
    const member=await registerFixtureAccount(memberContext,origin,{roles:['VIEWER']});
    const secondContext=await browser.newContext();
    const second=await registerFixtureAccount(secondContext,origin,{roles:['VIEWER']});
    page = await context.newPage(); page.setDefaultTimeout(10000); page.on('pageerror',error=>errors.push(error.message));
    await page.goto(`${origin}/platform/approval-roles`);
    await page.getByRole('heading',{name:'角色管理',exact:true}).waitFor();
    await page.getByText('尚无审批角色。新建角色后可选择成员。',{exact:true}).waitFor();
    const title='商品与价格配置运营审批角色——跨渠道营销活动负责人和业务规则维护人员';
    const edit=()=>page.getByRole('button',{name:`编辑审批角色 ${title}`,exact:true}).click();
    const save=async(status=200)=>{
      const response=page.waitForResponse(r=>r.url().includes('/api/v1/approval-roles')&&['POST','PUT'].includes(r.request().method())&&r.status()===status);
      await page.getByRole('button',{name:'保存审批角色',exact:true}).click();
      const result=await (await response).json();
      await page.getByRole('dialog',{name:/^(新建|编辑)审批角色$/}).waitFor({state:'hidden'});
      return result;
    };
    await page.getByRole('button',{name:'新建审批角色',exact:true}).click();
    await page.getByLabel('角色名称',{exact:true}).fill(title);
    await page.getByLabel('角色名称',{exact:true}).focus(); await page.keyboard.press('Tab');
    assert.equal(await page.getByLabel('角色说明',{exact:true}).evaluate(el=>el===document.activeElement),true);
    await page.getByLabel('角色说明',{exact:true}).fill('商品配置负责人\n负责商品和价格规则的日常审阅');
    for(const person of [member,second]){
      await page.getByLabel('检索人员',{exact:true}).fill(person.credentials.username);
      await page.getByRole('button',{name:'查询人员',exact:true}).click();
      await page.getByRole('checkbox',{name:`选择成员 ${person.credentials.username}`,exact:true}).check();
    }
    await page.getByRole('button',{name:'关闭',exact:true}).last().click();
    await page.getByRole('button',{name:'继续编辑',exact:true}).click();
    assert.equal(await page.getByLabel('角色名称',{exact:true}).inputValue(),title);
    let role=await save(201);assert.equal(role.members.length,2);
    checks.push('empty state, searchable real member selection, keyboard form order, unsaved close protection and real save');
    await page.route('**/api/v1/approval-roles?*',route=>route.abort('failed'));
    await page.getByRole('button',{name:'刷新角色',exact:true}).click();
    await page.getByRole('alert').filter({hasText:'Admin 连接或响应传输中断。'}).waitFor();
    assert.equal(await page.getByRole('button',{name:`编辑审批角色 ${title}`,exact:true}).isVisible(),true);
    await page.unroute('**/api/v1/approval-roles?*');
    await page.getByRole('button',{name:'重试',exact:true}).click();
    await page.getByRole('alert').filter({hasText:'Admin 连接或响应传输中断。'}).waitFor({state:'hidden'});
    checks.push('role directory read failure retains the last successful list and offers a working retry');
    await page.setViewportSize({width:390,height:844});
    const catalog=page.getByRole('region',{name:'审批角色列表',exact:true});
    await catalog.focus(); await page.keyboard.press('ArrowRight');
    assert.ok(await catalog.evaluate(el=>el.scrollLeft>0),'role catalog does not scroll by keyboard');
    const sticky=await page.getByRole('button',{name:`编辑审批角色 ${title}`,exact:true}).boundingBox();
    assert.ok(sticky && sticky.x>=0 && sticky.x+sticky.width<=390,'role action is not visible while scrolling');
    await page.mouse.move(0,0);
    await page.waitForFunction(()=>document.querySelectorAll('[data-sonner-toast]').length===0,undefined,{timeout:7000});
    await page.evaluate(async()=>Promise.all(document.getAnimations().map(animation=>animation.finished.catch(()=>{}))));
    assert.ok(await page.locator('#primary-navigation').evaluate(el=>el.getBoundingClientRect().right<=1 && getComputedStyle(el).visibility==='hidden'),'mobile navigation transition has not finished');
    await page.screenshot({path:path.join(output,'mobile-list-actions.png')});
    checks.push('390px role catalog scrolls with arrow keys while its edit action remains visible');
    await page.setViewportSize({width:1440,height:1000});
    await page.reload(); await edit();
    assert.equal(await page.getByLabel('角色名称',{exact:true}).inputValue(),title);
    assert.equal(await page.getByRole('list',{name:'已选择成员'}).getByRole('listitem').count(),2);
    // Revisit cached personnel searches, then fail a refresh at the network boundary.
    await page.getByLabel('检索人员',{exact:true}).fill(member.credentials.username);
    await page.getByRole('button',{name:'查询人员',exact:true}).click();
    await page.getByRole('checkbox',{name:`选择成员 ${member.credentials.username}`,exact:true}).waitFor();
    await page.getByLabel('检索人员',{exact:true}).fill(second.credentials.username);
    await page.getByRole('button',{name:'查询人员',exact:true}).click();
    await page.getByRole('checkbox',{name:`选择成员 ${second.credentials.username}`,exact:true}).waitFor();
    await page.route('**/api/v1/account-roles?*',route=>route.abort('failed'));
    await page.getByLabel('检索人员',{exact:true}).fill(member.credentials.username);
    await page.getByRole('button',{name:'查询人员',exact:true}).click();
    await page.getByRole('alert').filter({hasText:'Admin 连接或响应传输中断。'}).waitFor();
    assert.equal(await page.getByRole('list',{name:'已选择成员'}).getByRole('listitem').count(),2);
    assert.equal(await page.getByRole('checkbox',{name:`选择成员 ${member.credentials.username}`,exact:true}).isChecked(),true);
    await page.unroute('**/api/v1/account-roles?*');
    await page.getByRole('button',{name:'重试',exact:true}).click();
    await page.getByRole('alert').filter({hasText:'Admin 连接或响应传输中断。'}).waitFor({state:'hidden'});
    checks.push('personnel read failure retains cached search results and selected identities, then retries successfully');
    await stableScreenshot('desktop-members.png');
    await page.getByRole('button',{name:`移除成员 ${second.credentials.username}`,exact:true}).click();
    role=await save();assert.equal(role.members.length,1);
    checks.push('reload preserves role identity and members; removing one member saves through public API');
    await edit(); await page.getByLabel('角色说明',{exact:true}).fill('数据库明确回滚保留输入');
    const rolledBack=page.waitForResponse(r=>r.url().includes(`/api/v1/approval-roles/${role.id}`)&&r.request().method()==='PUT'&&r.status()===503);
    await page.getByRole('button',{name:'保存审批角色',exact:true}).click();
    assert.equal((await (await rolledBack).json()).error.code,'approval_role_not_saved');
    await page.getByRole('alert').filter({hasText:'本次尝试未保存'}).waitFor();
    assert.equal(await page.getByLabel('角色说明',{exact:true}).isEditable(),true,'known rollback must leave the form editable');
    assert.equal(await page.getByLabel('角色说明',{exact:true}).inputValue(),'数据库明确回滚保留输入');
    const afterRollback=await (await authenticatedRequest(context,origin,`/api/v1/approval-roles/${role.id}`)).json();
    assert.equal(afterRollback.version,role.version);assert.equal(afterRollback.description,role.description);
    await page.getByLabel('角色说明',{exact:true}).fill('明确失败后修正内容');
    role=await save();assert.equal(role.description,'明确失败后修正内容');
    checks.push('real database rollback returns definite failure, preserves editable inputs and allows a corrected save');
    await edit();
    await page.getByLabel('角色说明',{exact:true}).fill('本地意见保留');
    const changed=await authenticatedRequest(context,origin,`/api/v1/approval-roles/${role.id}`,{method:'PUT',headers:{'Idempotency-Key':'browser-concurrent-change'},data:{name:title,description:'另一位管理员刚更新',enabled:true,member_ids:role.members.map(m=>m.id),expected_version:role.version}});
    assert.equal(changed.status(),200);
    await page.getByRole('button',{name:'保存审批角色',exact:true}).click();
    await page.getByRole('button',{name:'查看最新角色内容',exact:true}).waitFor();
    assert.equal(await page.getByLabel('角色说明',{exact:true}).inputValue(),'本地意见保留');
    await page.getByRole('button',{name:'查看最新角色内容',exact:true}).click();
    await page.getByLabel('服务器最新角色').getByText('另一位管理员刚更新',{exact:true}).waitFor();
    role=await save();assert.equal(role.description,'本地意见保留');
    checks.push('stale version rejects overwrite, preserves input, exposes current content and requires explicit save');
    await edit(); await page.getByLabel('角色说明',{exact:true}).fill('响应丢失后保留原请求');
    const requests=[];
    await page.route(`**/api/v1/approval-roles/${role.id}`,async route=>{
      if(route.request().method()!=='PUT')return route.continue();
      requests.push({key:route.request().headers()['idempotency-key'],body:route.request().postData()});
      if(requests.length===1){const response=await route.fetch();assert.equal(response.status(),200);return route.abort('failed');}
      return route.continue();
    });
    await page.getByRole('button',{name:'保存审批角色',exact:true}).click();
    await page.getByRole('button',{name:'使用原请求重试',exact:true}).waitFor();
    assert.equal(await page.getByLabel('角色说明',{exact:true}).isDisabled(),true);
    await page.setViewportSize({width:390,height:844});
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'390px page overflows');
    await page.getByText('保存结果待确认。当前内容与原请求已保留，请使用原请求重试。',{exact:true}).scrollIntoViewIfNeeded();
    await stableScreenshot('mobile-unknown.png');
    await page.getByRole('button',{name:'使用原请求重试',exact:true}).click();
    await page.getByRole('dialog',{name:'编辑审批角色',exact:true}).waitFor({state:'hidden'});
    assert.equal(requests.length,2);assert.deepEqual(requests[0],requests[1]);
    await page.unroute(`**/api/v1/approval-roles/${role.id}`);
    checks.push('lost committed response preserves exact original key/body; explicit retry returns original result at 390px');
    await edit(); await page.getByLabel('角色说明',{exact:true}).fill('未送达仍保留的本地输入');
    let lost=true;
    await page.route(`**/api/v1/approval-roles/${role.id}`,async route=>{
      if(route.request().method()==='PUT' && lost){lost=false;return route.abort('failed');}
      return route.continue();
    });
    await page.getByRole('button',{name:'保存审批角色',exact:true}).click();
    await page.getByRole('button',{name:'使用原请求重试',exact:true}).waitFor();
    const latest=await (await authenticatedRequest(context,origin,`/api/v1/approval-roles/${role.id}`)).json();
    const intervening=await authenticatedRequest(context,origin,`/api/v1/approval-roles/${role.id}`,{method:'PUT',headers:{'Idempotency-Key':'browser-intervening-edit'},data:{name:title,description:'请求未送达时的其他修改',enabled:true,member_ids:latest.members.map(m=>m.id),expected_version:latest.version}});
    assert.equal(intervening.status(),200);
    await page.getByRole('button',{name:'使用原请求重试',exact:true}).click();
    await page.getByRole('button',{name:'查看最新角色内容',exact:true}).click();
    await page.getByLabel('服务器最新角色').getByText('请求未送达时的其他修改',{exact:true}).waitFor();
    assert.equal(await page.getByLabel('角色说明',{exact:true}).inputValue(),'未送达仍保留的本地输入');
    role=await save();await page.unroute(`**/api/v1/approval-roles/${role.id}`);
    checks.push('an undelivered uncertain request that later conflicts can return to latest-content review without losing input');
    await edit(); await page.getByLabel('角色说明',{exact:true}).fill('同账号登录恢复后继续编辑');
    await context.clearCookies();
    await page.getByRole('button',{name:'保存审批角色',exact:true}).click();
    await page.getByRole('heading',{name:'登录会话已中断',exact:true}).waitFor();
    assert.equal(await page.getByLabel('角色说明',{exact:true}).isVisible(),false);
    await page.getByLabel('用户名',{exact:true}).fill(admin.credentials.username);
    await page.getByLabel('密码',{exact:true}).fill(admin.credentials.password);
    await page.getByRole('button',{name:'登录',exact:true}).click();
    await page.getByLabel('角色说明',{exact:true}).waitFor();
    assert.equal(await page.getByLabel('角色说明',{exact:true}).inputValue(),'同账号登录恢复后继续编辑');
    await page.getByLabel('启用此审批角色',{exact:true}).uncheck();
    await page.getByLabel('角色名称',{exact:true}).focus(); await page.keyboard.press('Tab');
    assert.equal(await page.getByLabel('角色说明',{exact:true}).evaluate(el=>el===document.activeElement),true);
    await stableScreenshot('mobile-recovered.png');
    role=await save();assert.equal(role.enabled,false);
    checks.push('real missing-cookie interruption hides protected inputs, same-account login preserves input and members, mobile keyboard can disable and save');
    await edit(); await page.getByLabel('启用此审批角色',{exact:true}).check();role=await save();assert.equal(role.enabled,true);
    await edit(); await page.getByRole('button',{name:'删除审批角色',exact:true}).click();
    const confirmation=page.getByRole('alertdialog',{name:'删除审批角色？',exact:true});
    assert.equal(await confirmation.getByRole('button',{name:'取消',exact:true}).evaluate(el=>el===document.activeElement),true);
    await confirmation.getByRole('button',{name:'确认删除角色',exact:true}).click();
    await page.getByRole('dialog',{name:'编辑审批角色',exact:true}).waitFor({state:'hidden'});
    await page.getByText('尚无审批角色。新建角色后可选择成员。',{exact:true}).waitFor();
    checks.push('enable restoration and unreferenced deletion with cancel-first keyboard confirmation');
    // Another enabled administrator can revoke this operator during an open draft.
    await setFixtureRoles(context,origin,second.accountID,['ADMIN']);
    await page.getByRole('button',{name:'新建审批角色',exact:true}).click();
    await page.getByLabel('角色名称',{exact:true}).fill('撤权期间私有输入');
    await setFixtureRoles(secondContext,origin,admin.accountID,['VIEWER']);
    await page.getByRole('button',{name:'保存审批角色',exact:true}).click();
    await page.getByText('管理员权限已撤销，已输入内容保留，暂不能保存。',{exact:true}).waitFor();
    assert.equal(await page.getByLabel('角色名称',{exact:true}).inputValue(),'撤权期间私有输入');
    assert.equal(await page.getByRole('button',{name:'保存审批角色',exact:true}).isDisabled(),true);
    // An account switch removes the previous account's in-memory draft entirely.
    await context.clearCookies();await context.addCookies(await secondContext.cookies());
    await page.evaluate(()=>window.dispatchEvent(new CustomEvent('rcc:business-session-invalid',{detail:{code:'account_changed'}})));
    await page.getByRole('dialog',{name:'新建审批角色',exact:true}).waitFor({state:'detached'});
    await page.getByRole('button',{name:'新建审批角色',exact:true}).click();
    assert.equal(await page.getByLabel('角色名称',{exact:true}).inputValue(),'');
    checks.push('revocation preserves draft and disables save; switching real accounts discards private draft');
    assert.deepEqual(errors,[]);
    fs.writeFileSync(path.join(output,'result.json'),JSON.stringify({browser:browser.version(),checks,errors},null,2));console.log(JSON.stringify({checks,errors}));
  }catch(error){if(page){await page.screenshot({path:path.join(output,'failure.png'),fullPage:true}).catch(()=>{});fs.writeFileSync(path.join(output,'failure.txt'),await page.locator('body').innerText().catch(()=>''));}throw error;}
  finally { await browser.close(); }
})().catch(error=>{console.error(error);process.exitCode=1});
